(function () {
  const candidateStatusFlow = [
    "系统推荐",
    "初筛",
    "待试镜",
    "已提交",
    "待评价",
    "复试",
    "待导演确认",
    "待制片确认",
    "已定",
  ];

  const users = [
    { id: "u-admin", name: "选角导演组", role: "admin", organization: "正午阳光" },
    { id: "u-actor", name: "罗清弦", role: "actor", talentId: "luo-qingxian" },
    { id: "u-agent", name: "禾木经纪", role: "agent", talentIds: ["luo-qingxian", "liang-yue"] },
  ];

  const projects = [
    {
      id: "jianghe",
      title: "《江河人间》",
      type: "剧集",
      genre: "年代现实主义",
      episodeCount: 36,
      episodeLength: 45,
      director: "导演组待定",
      producer: "制片中心",
      writer: "文学策划组",
      platform: "长视频平台",
      budgetLevel: "medium",
      startDate: "2026-06-18",
      shootingPeriod: "110天",
      location: "山东 / 江苏 / 北京",
      castingStrategy: ["演技优先", "正午风格优先", "低风险优先"],
      status: "选角中",
      progress: 64,
    },
  ];

  const roles = [
    {
      id: "su-jinyu",
      projectId: "jianghe",
      name: "苏锦渔",
      type: "女主",
      gender: "女",
      ageRange: "28-34",
      roleLevel: "S",
      identity: "县城青年干部，后期进入市级改革小组",
      tone: "外冷内热，处理危机时克制，面对家人时有突然柔软的一面。",
      startState: "被动接手复杂项目，对人和事保持距离。",
      middleChange: "在基层矛盾中逐步建立判断，也开始暴露脆弱。",
      endState: "能承担决策代价，完成从旁观者到行动者的转变。",
      motivation: "证明自己不是被安排的人，而是能解决问题的人。",
      relationships: ["陈述：互相试探的工作搭档", "何燕燕：民间信息入口", "林峭：年轻下属"],
      opponents: ["陈述", "何燕燕", "项目反对方"],
      performanceChallenges: ["克制表达", "长段台词", "情绪转折", "群戏控制"],
      keyScenes: ["母女争执后的独处戏", "公开协调会", "雨夜找证据"],
      auditionFocus: ["长段台词", "情绪转折", "年代生活质感"],
      mustHave: ["现实质感", "台词稳定", "能压住群戏"],
      flexible: ["年龄可上浮2岁", "城市口音可训练"],
      traits: ["现实质感", "微表情", "强台词", "能压住群戏"],
      status: "复试中",
    },
    {
      id: "chen-shu",
      projectId: "jianghe",
      name: "陈述",
      type: "男主",
      gender: "男",
      ageRange: "32-40",
      roleLevel: "S",
      identity: "基层干部出身的项目负责人",
      tone: "稳、倔、有疲惫感，但内在有行动力。",
      startState: "熟悉基层规则，习惯独自扛事。",
      middleChange: "与苏锦渔从互不信任转向共同承担。",
      endState: "放下孤勇，学会把问题交给团队。",
      motivation: "保护自己服务过的人，也保护项目不被形式主义拖垮。",
      relationships: ["苏锦渔：工作搭档", "何燕燕：旧识", "林峭：带教对象"],
      opponents: ["苏锦渔", "上级考核组"],
      performanceChallenges: ["方言自然度", "疲惫状态", "低声争辩", "沉默段落"],
      keyScenes: ["家庭冲突戏", "会议沉默", "夜间走访"],
      auditionFocus: ["方言自然度", "疲惫状态", "群像关系"],
      mustHave: ["生活流", "方言自然", "基层可信度"],
      flexible: ["身高不做硬限制", "市场知名度可低"],
      traits: ["生活流", "方言", "沉稳", "抗压"],
      status: "试镜中",
    },
    {
      id: "he-yanyan",
      projectId: "jianghe",
      name: "何燕燕",
      type: "重要配角",
      gender: "女",
      ageRange: "40-48",
      roleLevel: "A",
      identity: "县城小店老板，民间关系网络核心",
      tone: "爽利、精明、心软，喜剧节奏藏在日常里。",
      startState: "只想护住小店和家人，不愿卷入项目。",
      middleChange: "被迫成为信息关键节点。",
      endState: "用自己的方式完成一次体面选择。",
      motivation: "给家人留退路，也给自己争口气。",
      relationships: ["陈述：旧识", "苏锦渔：从防备到信任", "街坊群像"],
      opponents: ["陈述", "邻里纠纷对象"],
      performanceChallenges: ["烟火气", "快节奏对白", "喜剧分寸", "人物反差"],
      keyScenes: ["饭桌群戏", "店门口争执", "深夜和苏锦渔谈心"],
      auditionFocus: ["烟火气", "节奏", "人物反差"],
      mustHave: ["市井感", "喜剧不过火", "台词节奏"],
      flexible: ["年龄感可放宽", "地域口音可转化"],
      traits: ["喜剧分寸", "烟火气", "反差", "即兴"],
      status: "推荐中",
    },
    {
      id: "lin-qiao",
      projectId: "jianghe",
      name: "林峭",
      type: "青年角色",
      gender: "女",
      ageRange: "19-24",
      roleLevel: "B",
      identity: "刚入社会的实习生",
      tone: "自尊强，容易紧绷，后期成长明显。",
      startState: "怕犯错，急于证明自己。",
      middleChange: "经历一次公开失败后开始真正进入工作。",
      endState: "能独立完成关键材料收集。",
      motivation: "从被看见到真的有用。",
      relationships: ["苏锦渔：上下级", "陈述：带教对象", "年轻同事"],
      opponents: ["自我怀疑", "同辈压力"],
      performanceChallenges: ["生涩感", "眼神变化", "成长弧线", "镜头松弛"],
      keyScenes: ["入职第一天", "情绪崩溃后的收束", "独立汇报"],
      auditionFocus: ["生涩感", "眼神变化", "成长弧线"],
      mustHave: ["自然表演", "清透", "成长可信"],
      flexible: ["表演经验可少", "普通话可训练"],
      traits: ["清透", "成长弧", "镜头感", "自然表演"],
      status: "试镜中",
    },
  ];

  const talents = [
    {
      id: "luo-qingxian",
      name: "罗清弦",
      gender: "女",
      age: 31,
      perceivedAge: "28-34",
      height: 168,
      hometown: "辽宁",
      city: "北京",
      agency: "禾木经纪",
      agentName: "周敏",
      contact: "138****2468",
      education: "中央戏剧学院",
      scheduleStatus: "6月上旬可进组",
      feeRange: "中",
      profileCompletion: 86,
      auditStatus: "已入库",
      riskLevel: "low",
      portrait: "assets/portrait-luo.png",
      tags: ["现实质感", "微表情", "强台词"],
      skills: ["长段台词", "钢琴", "驾驶"],
      dialects: ["普通话", "东北方言"],
      works: ["《江河之后》饰 记者沈知", "《北城小巷》饰 女主姐姐", "话剧《冬夜》主演"],
      materials: ["表演片段", "生活照", "台词音频", "档期表"],
      note: "眼神控制很好，情绪不是外放型，适合苏锦渔的克制感。",
    },
    {
      id: "xu-mingyuan",
      name: "许明远",
      gender: "男",
      age: 36,
      perceivedAge: "33-40",
      height: 180,
      hometown: "山东",
      city: "青岛",
      agency: "山海演员工作室",
      agentName: "韩青",
      contact: "139****6631",
      education: "上海戏剧学院",
      scheduleStatus: "5月底至7月可协调",
      feeRange: "中",
      profileCompletion: 78,
      auditStatus: "已入库",
      riskLevel: "medium",
      portrait: "assets/portrait-xu.png",
      tags: ["生活流", "方言", "沉稳"],
      skills: ["山东话", "驾驶", "篮球"],
      dialects: ["普通话", "胶东方言"],
      works: ["《海风县》饰 刘卫东", "《现场》饰 刑警队长", "《桥南桥北》客串"],
      materials: ["表演片段", "自我介绍", "档期表"],
      note: "身上有基层人物的真实感，表达不端着。",
    },
    {
      id: "jiang-wenxi",
      name: "江闻溪",
      gender: "女",
      age: 43,
      perceivedAge: "40-48",
      height: 164,
      hometown: "江苏",
      city: "南京",
      agency: "自由演员",
      agentName: "本人",
      contact: "137****8120",
      education: "南京艺术学院",
      scheduleStatus: "6月中旬后可进组",
      feeRange: "低",
      profileCompletion: 62,
      auditStatus: "待补充",
      riskLevel: "low",
      portrait: "assets/portrait-jiang.png",
      tags: ["烟火气", "喜剧分寸", "即兴"],
      skills: ["方言", "即兴", "小品"],
      dialects: ["普通话", "南京话"],
      works: ["《老街味道》饰 周老板", "《家门口》饰 方萍", "小剧场《人间厨房》"],
      materials: ["生活照", "台词音频"],
      note: "人物身上有很自然的市井气，喜剧不抢戏。",
    },
    {
      id: "tang-xiaorui",
      name: "唐晓蕊",
      gender: "女",
      age: 22,
      perceivedAge: "19-23",
      height: 166,
      hometown: "浙江",
      city: "上海",
      agency: "新声计划",
      agentName: "顾然",
      contact: "136****7450",
      education: "上海视觉艺术学院",
      scheduleStatus: "可随时试镜，进组需提前15天",
      feeRange: "低",
      profileCompletion: 74,
      auditStatus: "已入库",
      riskLevel: "low",
      portrait: "assets/portrait-tang.png",
      tags: ["清透", "成长弧", "镜头感"],
      skills: ["舞蹈", "短跑", "英语"],
      dialects: ["普通话"],
      works: ["《夏天的台阶》饰 林黎", "短片《白色车站》主演", "广告及平面拍摄"],
      materials: ["表演片段", "生活照", "自我介绍"],
      note: "镜头前很松，生涩感不是表演出来的。",
    },
    {
      id: "shen-zhou",
      name: "沈洲",
      gender: "男",
      age: 39,
      perceivedAge: "36-43",
      height: 178,
      hometown: "陕西",
      city: "西安",
      agency: "陇声文化",
      agentName: "马骁",
      contact: "135****7219",
      education: "西安外事学院",
      scheduleStatus: "6月档期紧，可争取",
      feeRange: "中",
      profileCompletion: 70,
      auditStatus: "已入库",
      riskLevel: "medium",
      portrait: "assets/portrait-shen.png",
      tags: ["沉稳", "抗压", "方言"],
      skills: ["陕西话", "旁白", "驾驶"],
      dialects: ["普通话", "陕西话"],
      works: ["《黄土线》饰 马主任", "《西口》饰 乔梁", "纪录片旁白多部"],
      materials: ["台词音频", "档期表"],
      note: "声音条件好，人物可信。",
    },
    {
      id: "liang-yue",
      name: "梁玥",
      gender: "女",
      age: 29,
      perceivedAge: "27-33",
      height: 170,
      hometown: "浙江",
      city: "杭州",
      agency: "青禾影视",
      agentName: "魏黎",
      contact: "137****9251",
      education: "北京电影学院",
      scheduleStatus: "已锁 6月1日进组",
      feeRange: "中",
      profileCompletion: 94,
      auditStatus: "重点关注",
      riskLevel: "low",
      portrait: "assets/portrait-liang.png",
      tags: ["现实质感", "自然表演", "能压住群戏"],
      skills: ["台词", "舞台剧", "骑行"],
      dialects: ["普通话", "杭州话"],
      works: ["《南方来信》饰 顾宁", "《第七张照片》饰 陈望", "《春潮》舞台版"],
      materials: ["表演片段", "生活照", "台词音频", "档期表", "合同信息"],
      note: "综合稳定，已进入备选锁定。",
    },
  ];

  const candidates = [
    {
      id: "c-luo-su",
      projectId: "jianghe",
      roleId: "su-jinyu",
      talentId: "luo-qingxian",
      source: "system",
      recommendationType: "reputation",
      totalScore: 94,
      scores: { temperament: 96, ageFit: 92, acting: 95, realism: 93, relationshipFit: 90, schedule: 86, market: 78, risk: 18 },
      fitReason: "克制型表达和人物前期疏离感高度贴合，长段台词稳定。",
      riskReason: "档期需与另一部剧协调，但经纪方反馈可优先。",
      evidence: ["《北城小巷》第12集长对白", "话剧《冬夜》独白段"],
      status: "复试",
      internalNotes: "复试加母女争执后的独处戏。",
      directorOpinion: "气质准，情绪再压一点更好。",
      producerOpinion: "片酬可控，档期需锁。",
      castingOpinion: "优先推进。",
    },
    {
      id: "c-liang-su",
      projectId: "jianghe",
      roleId: "su-jinyu",
      talentId: "liang-yue",
      source: "manual",
      recommendationType: "safe",
      totalScore: 88,
      scores: { temperament: 86, ageFit: 90, acting: 88, realism: 89, relationshipFit: 84, schedule: 92, market: 80, risk: 14 },
      fitReason: "人物外在更柔和，适合偏温润版本的苏锦渔。",
      riskReason: "已锁进组，需要确认是否可承接主线强度。",
      evidence: ["《南方来信》家庭冲突戏"],
      status: "待导演确认",
      internalNotes: "导演看完复试后再与罗清弦二选一。",
      directorOpinion: "稳定但锋利度略弱。",
      producerOpinion: "档期最稳。",
      castingOpinion: "备选锁定。",
    },
    {
      id: "c-xu-chen",
      projectId: "jianghe",
      roleId: "chen-shu",
      talentId: "xu-mingyuan",
      source: "system",
      recommendationType: "safe",
      totalScore: 91,
      scores: { temperament: 90, ageFit: 93, acting: 88, realism: 94, relationshipFit: 87, schedule: 82, market: 72, risk: 32 },
      fitReason: "基层人物真实感强，方言自然，沉默段落可信。",
      riskReason: "市场声量偏弱，需要看与女主组合张力。",
      evidence: ["《海风县》走访戏", "《现场》低声争辩段"],
      status: "待评价",
      internalNotes: "试镜视频已回传，待导演评价。",
      directorOpinion: "等组合测试。",
      producerOpinion: "片酬安全。",
      castingOpinion: "建议进入组合测试。",
    },
    {
      id: "c-shen-chen",
      projectId: "jianghe",
      roleId: "chen-shu",
      talentId: "shen-zhou",
      source: "manual",
      recommendationType: "backup",
      totalScore: 86,
      scores: { temperament: 88, ageFit: 84, acting: 86, realism: 88, relationshipFit: 82, schedule: 58, market: 68, risk: 42 },
      fitReason: "声音条件和人物可信度好，可做偏稳版本。",
      riskReason: "6月档期紧，需尽快确认。",
      evidence: ["《黄土线》基层干部线"],
      status: "初筛",
      internalNotes: "先联系经纪确认窗口期。",
      directorOpinion: "可看。",
      producerOpinion: "档期风险需降。",
      castingOpinion: "备用推进。",
    },
    {
      id: "c-jiang-he",
      projectId: "jianghe",
      roleId: "he-yanyan",
      talentId: "jiang-wenxi",
      source: "system",
      recommendationType: "reputation",
      totalScore: 93,
      scores: { temperament: 94, ageFit: 92, acting: 90, realism: 96, relationshipFit: 88, schedule: 74, market: 60, risk: 16 },
      fitReason: "市井气自然，喜剧节奏不抢戏，适合群像关系。",
      riskReason: "素材不完整，需要补表演片段。",
      evidence: ["小剧场《人间厨房》饭桌戏"],
      status: "系统推荐",
      internalNotes: "优先补视频资料。",
      directorOpinion: "想看现场。",
      producerOpinion: "性价比高。",
      castingOpinion: "推荐初试。",
    },
    {
      id: "c-tang-lin",
      projectId: "jianghe",
      roleId: "lin-qiao",
      talentId: "tang-xiaorui",
      source: "agent_submission",
      recommendationType: "newcomer",
      totalScore: 90,
      scores: { temperament: 89, ageFit: 96, acting: 82, realism: 86, relationshipFit: 88, schedule: 92, market: 66, risk: 18 },
      fitReason: "生涩感自然，镜头前松，成长线可信。",
      riskReason: "后半段成长需要再压甜感。",
      evidence: ["短片《白色车站》结尾段"],
      status: "已提交",
      internalNotes: "待选角导演先评。",
      directorOpinion: "可做备选。",
      producerOpinion: "新人成本友好。",
      castingOpinion: "建议复试。",
    },
  ];

  const auditions = [
    {
      id: "a-1",
      projectId: "jianghe",
      roleId: "chen-shu",
      talentId: "xu-mingyuan",
      candidateId: "c-xu-chen",
      type: "现场试镜",
      script: "陈述夜间走访片段",
      requirement: "方言自然度、沉默段落、家庭冲突戏",
      deadline: "2026-05-27T10:30",
      location: "A 棚",
      status: "待评价",
      videoUrl: "已上传",
      submittedAt: "2026-05-27T09:40",
    },
    {
      id: "a-2",
      projectId: "jianghe",
      roleId: "lin-qiao",
      talentId: "tang-xiaorui",
      candidateId: "c-tang-lin",
      type: "自录初试",
      script: "入职第一天",
      requirement: "情绪崩溃后的收束",
      deadline: "2026-05-27T14:00",
      location: "线上提交",
      status: "已提交",
      videoUrl: "已上传",
      submittedAt: "2026-05-26T21:12",
    },
    {
      id: "a-3",
      projectId: "jianghe",
      roleId: "su-jinyu",
      talentId: "luo-qingxian",
      candidateId: "c-luo-su",
      type: "复试",
      script: "母女争执、独处段落",
      requirement: "长台词与情绪转折",
      deadline: "2026-05-28T16:20",
      location: "B 棚",
      status: "已邀请",
      videoUrl: "",
      submittedAt: "",
    },
  ];

  const auditionReviews = [
    {
      id: "r-1",
      auditionId: "a-1",
      reviewerId: "u-admin",
      reviewerRole: "casting_director",
      scores: { lines: 86, emotion: 84, rhythm: 88, eyes: 82, body: 80, realism: 93, understanding: 86, interaction: 84, adjustment: 82, stability: 90 },
      comment: "真实感强，组合测试前需要再看与苏锦渔的压迫和松弛。",
      decision: "callback",
    },
  ];

  const combinationTests = [
    {
      id: "ct-1",
      projectId: "jianghe",
      relationshipType: "男女主",
      roleIds: ["su-jinyu", "chen-shu"],
      talentIds: ["luo-qingxian", "xu-mingyuan"],
      testScene: "雨夜找证据后车内争执",
      videoUrl: "待上传",
      scores: { credibility: 88, tension: 91, intimacy: 70, pressure: 86, realism: 92, conflict: 89, balance: 84, rhythm: 86 },
      conclusion: "基本成立",
      notes: "工作关系成立，亲密感需要二次复试观察。",
    },
  ];

  const castPlans = [
    {
      id: "cp-a",
      projectId: "jianghe",
      name: "方案A：稳妥阵容",
      type: "safe",
      cast: [
        { roleId: "su-jinyu", talentId: "liang-yue" },
        { roleId: "chen-shu", talentId: "xu-mingyuan" },
        { roleId: "he-yanyan", talentId: "jiang-wenxi" },
        { roleId: "lin-qiao", talentId: "tang-xiaorui" },
      ],
      budgetEstimate: "中",
      scheduleFeasibility: 86,
      styleConsistency: 88,
      relationshipScore: 82,
      marketValue: "口碑稳定，营销压力中等",
      biggestRisk: "主角组合新鲜感一般",
      backupPlan: "苏锦渔可替换为罗清弦",
      recommendation: "适合稳妥推进导演确认。",
    },
    {
      id: "cp-b",
      projectId: "jianghe",
      name: "方案B：突破阵容",
      type: "breakthrough",
      cast: [
        { roleId: "su-jinyu", talentId: "luo-qingxian" },
        { roleId: "chen-shu", talentId: "xu-mingyuan" },
        { roleId: "he-yanyan", talentId: "jiang-wenxi" },
        { roleId: "lin-qiao", talentId: "tang-xiaorui" },
      ],
      budgetEstimate: "中低",
      scheduleFeasibility: 78,
      styleConsistency: 91,
      relationshipScore: 86,
      marketValue: "角色新鲜，适合口碑发酵",
      biggestRisk: "女主档期协调",
      backupPlan: "若档期失败切回方案A",
      recommendation: "更贴近正午现实主义质感。",
    },
  ];

  const risks = [
    {
      id: "risk-1",
      talentId: "xu-mingyuan",
      projectId: "jianghe",
      roleId: "chen-shu",
      type: "市场接受度",
      level: "中",
      description: "市场声量偏弱，主线宣发需更多角色卖点支持。",
      evidence: "近三年主演作品讨论度有限。",
      suggestion: "用组合测试和角色高光片段增强推荐依据。",
      resolved: false,
      recorder: "选角导演组",
      recordedAt: "2026-05-23",
    },
    {
      id: "risk-2",
      talentId: "shen-zhou",
      projectId: "jianghe",
      roleId: "chen-shu",
      type: "档期冲突",
      level: "高",
      description: "6月已有口头邀约，可能与开机窗口冲突。",
      evidence: "经纪人口头反馈。",
      suggestion: "48小时内确认档期，否则转备用。",
      resolved: false,
      recorder: "制片中心",
      recordedAt: "2026-05-24",
    },
  ];

  const timelineEvents = [
    { id: "t-1", projectId: "jianghe", roleId: "su-jinyu", talentId: "luo-qingxian", text: "罗清弦进入复试，补充母女争执段落。", at: "2026-05-24 10:30", actor: "选角导演组" },
    { id: "t-2", projectId: "jianghe", roleId: "chen-shu", talentId: "xu-mingyuan", text: "许明远提交现场试镜视频，等待导演评价。", at: "2026-05-24 11:15", actor: "试镜统筹" },
    { id: "t-3", projectId: "jianghe", roleId: "lin-qiao", talentId: "tang-xiaorui", text: "唐晓蕊经纪端完成自录试镜提交。", at: "2026-05-23 21:12", actor: "新声计划" },
  ];

  window.NoonSeed = {
    candidateStatusFlow,
    users,
    projects,
    roles,
    talents,
    candidates,
    auditions,
    auditionReviews,
    combinationTests,
    castPlans,
    risks,
    timelineEvents,
  };
})();
